[package]
name = "tsc_rs_symbols"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Symbol table and binding for tsc-rs"

[dependencies]
tsc_rs_ast = { path = "../tsc_rs_ast" }
rustc-hash = "2"

[dev-dependencies]
tsc_rs_parser = { path = "../tsc_rs_parser" }
