//! tsc-compatible source map mappings, synthesized after emission.
//!
//! tsc maps both ends of every node it prints (and of each comment), plus
//! the closing brace of a function body. Our emitter keeps the source's
//! layout and copies most text, so instead of threading positions through
//! every printing path, the mappings are recovered afterwards: source and
//! output tokens are aligned (the output keeps the source's tokens, minus
//! erased syntax, plus synthesized code), and each node maps the output
//! position of its first and last surviving token. The CommonJS/AMD module
//! transform is covered by rules for the statements it synthesizes
//! (`exports.x = …`, `const m = require(…)`, export hoists).
//!
//! The result is the raw mapping sequence in tsc's emission order; the
//! generator applies tsc's coalescing rules when encoding.

use tsc_rs_ast::{
    ArrayPatElem, ArrowBody, ClassDecl, ClassMemberKind, ExportDeclKind, Expr, ExprKind, FnDecl,
    ForInOfLeft, ForInit, ImportClause, ModuleBody, ObjLitProp, ObjPatProp, Param, Pat, PatKind,
    PropName, SourceFile, Span, Stmt, StmtKind,
};

/// One mapping: generated byte offset → source byte offset.
type Raw = (usize, u32);

/// A token's byte range.
#[derive(Clone, Copy)]
struct Tok {
    start: usize,
    end: usize,
}

/// Generated (line, column) → source (line, column) mappings, in emission
/// order.
pub(crate) fn synthesize(source: &str, file: &SourceFile, js: &str) -> Vec<(u32, u32, u32, u32)> {
    let src_toks = tokenize(source);
    let js_toks = tokenize(js);
    let synthetic = synthetic_lines(js);
    let align = align_tokens(source, &src_toks, js, &js_toks, &synthetic);

    // Statements the module transform replaces wholesale.
    let mut require_stmts: Vec<(Span, String)> = Vec::new();
    let mut export_decls: Vec<(Span, String, bool)> = Vec::new();
    let mut exported_vars: Vec<(String, Span)> = Vec::new();
    collect_module_statements(
        &file.statements,
        &mut require_stmts,
        &mut export_decls,
        &mut exported_vars,
    );

    let mut walker = SpanWalker {
        spans: Vec::new(),
        brace_tokens: Vec::new(),
    };
    for stmt in &file.statements {
        walker.stmt(stmt);
    }
    let SpanWalker {
        spans,
        brace_tokens,
    } = walker;

    // An `export` wrapper and the declaration it wraps print as one node.
    let export_ranges: Vec<Span> = export_spans(&file.statements);
    let mut spans: Vec<Span> = spans
        .into_iter()
        .filter(|span| span.end > span.start)
        .filter(|span| {
            !export_ranges
                .iter()
                .any(|outer| span.end == outer.end && span.start > outer.start)
        })
        .filter(|span| {
            !require_stmts
                .iter()
                .any(|(stmt, _)| stmt.start <= span.start && span.end <= stmt.end)
        })
        .collect();
    // Property names after `.` are identifier nodes of their own.
    for (index, tok) in src_toks.iter().enumerate() {
        if &source[tok.start..tok.end] == "." {
            if let Some(next) = src_toks.get(index + 1) {
                if source[next.start..]
                    .starts_with(|c: char| c.is_alphabetic() || c == '_' || c == '$')
                {
                    spans.push(Span::new(next.start as u32, next.end as u32));
                }
            }
        }
    }
    spans.sort_by(|a, b| a.start.cmp(&b.start).then(b.end.cmp(&a.end)));
    spans.dedup();

    let js_aligned: Vec<bool> = {
        let mut aligned = vec![false; js_toks.len()];
        for target in align.iter().flatten() {
            aligned[*target] = true;
        }
        aligned
    };
    let first_index = |pos: usize| src_toks.partition_point(|tok| tok.start < pos);
    // Output range of the surviving tokens of a source span.
    let output_range = |span: Span| -> Option<(usize, usize)> {
        let lo = first_index(span.start as usize);
        let hi = src_toks.partition_point(|tok| tok.end <= span.end as usize);
        let first = (lo..hi).find(|&i| align[i].is_some())?;
        let last = (lo..hi).rev().find(|&i| align[i].is_some())?;
        let first_js = align[first]?;
        let mut start = js_toks[first_js].start;
        // An identifier reference the module transform rewrote to
        // `exports.x` maps from the start of the rewrite.
        let declared = first > 0
            && matches!(
                &source[src_toks[first - 1].start..src_toks[first - 1].end],
                "." | "var" | "let" | "const" | "function" | "class"
            );
        if !declared
            && first_js >= 2
            && &js[js_toks[first_js - 1].start..js_toks[first_js - 1].end] == "."
            && &js[js_toks[first_js - 2].start..js_toks[first_js - 2].end] == "exports"
            && !js_aligned[first_js - 1]
        {
            start = js_toks[first_js - 2].start;
        }
        Some((start, js_toks[align[last]?].end))
    };

    // Pre-order: a node's start, its children, then its end.
    let mut raw: Vec<Raw> = Vec::new();
    let mut open: Vec<(Span, usize)> = Vec::new();
    for span in spans {
        while open
            .last()
            .is_some_and(|(outer, _)| outer.end <= span.start)
        {
            let (outer, end) = open.pop().unwrap();
            raw.push((end, outer.end));
        }
        let Some((start, end)) = output_range(span) else {
            continue;
        };
        raw.push((start, span.start));
        open.push((span, end));
    }
    while let Some((outer, end)) = open.pop() {
        raw.push((end, outer.end));
    }

    // A function body's closing brace is printed as a mapped token.
    for brace in brace_tokens {
        let index = first_index(brace as usize);
        if src_toks
            .get(index)
            .is_some_and(|tok| tok.start == brace as usize)
        {
            if let Some(js_index) = align[index] {
                raw.push((js_toks[js_index].start, brace));
            }
        }
    }

    // Comments: both ends, matched to the output in order.
    let src_comments = comment_ranges(source);
    let js_comments = comment_ranges(js);
    let mut next = 0;
    for comment in &src_comments {
        let text = &source[comment.start..comment.end];
        if let Some(found) = (next..js_comments.len())
            .find(|&k| &js[js_comments[k].start..js_comments[k].end] == text)
        {
            raw.push((js_comments[found].start, comment.start as u32));
            raw.push((js_comments[found].end, comment.end as u32));
            next = found + 1;
        }
    }

    // Statements synthesized by the module transform.
    let mut leading: Vec<Raw> = Vec::new();
    let mut line_start = 0;
    for line in js.split_inclusive('\n') {
        let body = line.trim_end_matches(['\n', '\r']);
        let indent = body.len() - body.trim_start().len();
        let text = body.trim_start();
        let (start, end) = (line_start + indent, line_start + body.len());
        line_start += line.len();
        if let Some(rest) = text.strip_prefix("exports.") {
            let Some((name, rhs)) = rest.split_once(" = ") else {
                continue;
            };
            let rhs = rhs.trim_end_matches(';');
            if let Some((span, _, _)) = export_decls
                .iter()
                .find(|(_, decl_name, _)| decl_name == name && rhs == name)
            {
                raw.push((start, span.start));
                raw.push((end, span.end));
            } else if rhs != name && !rhs.contains("void 0") {
                if let Some((_, declarator)) = exported_vars.iter().find(|(var, _)| var == name) {
                    leading.push((start, declarator.start));
                }
            }
        } else if let Some(rest) = text
            .strip_prefix("const ")
            .or_else(|| text.strip_prefix("var "))
        {
            let Some((name, rhs)) = rest.split_once(" = ") else {
                continue;
            };
            if rhs.starts_with("require(") {
                if let Some((span, _)) = require_stmts.iter().find(|(_, alias)| alias == name) {
                    raw.push((start, span.start));
                    raw.push((end, span.end));
                }
            }
        }
    }
    leading.extend(raw);
    let mut raw = leading;

    // Generation order; recording order breaks ties (the generator's
    // coalescing depends on it).
    raw.sort_by_key(|(generated, _)| *generated);
    let js_lines = LineStarts::new(js);
    let src_lines = LineStarts::new(source);
    raw.into_iter()
        .map(|(generated, original)| {
            let (gen_line, gen_col) = js_lines.line_col(generated);
            let (src_line, src_col) = src_lines.line_col(original as usize);
            (gen_line, gen_col, src_line, src_col)
        })
        .collect()
}

/// Top-level module statements the CommonJS/AMD transform rewrites:
/// `import x = require(…)` (span, alias); exported classes/functions
/// (span, name, is_class); exported `var`s (name, declarator span).
fn collect_module_statements(
    statements: &[Stmt],
    require_stmts: &mut Vec<(Span, String)>,
    export_decls: &mut Vec<(Span, String, bool)>,
    exported_vars: &mut Vec<(String, Span)>,
) {
    for stmt in statements {
        match &stmt.kind {
            StmtKind::Import(import) => {
                if let ImportClause::Require(alias) = &import.specifiers {
                    require_stmts.push((stmt.span, alias.clone()));
                }
            }
            StmtKind::Export(export) => {
                let ExportDeclKind::Decl(inner) = &export.kind else {
                    continue;
                };
                match &inner.kind {
                    StmtKind::ClassDecl(class) => {
                        if let Some(name) = &class.name {
                            export_decls.push((stmt.span, name.clone(), true));
                        }
                    }
                    StmtKind::FnDecl(function) => {
                        if let Some(name) = &function.name {
                            export_decls.push((stmt.span, name.clone(), false));
                        }
                    }
                    StmtKind::Var(var) => {
                        for declarator in &var.declarations {
                            if let PatKind::Ident(name) = &declarator.name.kind {
                                exported_vars.push((name.to_string(), declarator.span));
                            }
                        }
                    }
                    StmtKind::Import(import) => {
                        if let ImportClause::Require(alias) = &import.specifiers {
                            require_stmts.push((stmt.span, alias.clone()));
                        }
                    }
                    _ => {}
                }
            }
            _ => {}
        }
    }
}

fn export_spans(statements: &[Stmt]) -> Vec<Span> {
    let mut out = Vec::new();
    fn visit(statements: &[Stmt], out: &mut Vec<Span>) {
        for stmt in statements {
            match &stmt.kind {
                StmtKind::Export(export) => {
                    if matches!(
                        export.kind,
                        ExportDeclKind::Decl(_) | ExportDeclKind::DefaultDecl(_)
                    ) {
                        out.push(stmt.span);
                    }
                }
                StmtKind::ModuleDecl(module) => {
                    let mut body = module.body.as_ref();
                    while let Some(ModuleBody::Module(inner)) = body {
                        body = inner.body.as_ref();
                    }
                    if let Some(ModuleBody::Block(statements)) = body {
                        visit(statements, out);
                    }
                }
                _ => {}
            }
        }
    }
    visit(statements, &mut out);
    out
}

/// Collects the spans of every printable node, and the closing-brace
/// positions of function bodies.
struct SpanWalker {
    spans: Vec<Span>,
    brace_tokens: Vec<u32>,
}

impl SpanWalker {
    fn stmts(&mut self, statements: &[Stmt]) {
        for stmt in statements {
            self.stmt(stmt);
        }
    }

    fn stmt(&mut self, stmt: &Stmt) {
        self.spans.push(stmt.span);
        match &stmt.kind {
            StmtKind::Var(var) => {
                for declarator in &var.declarations {
                    self.spans.push(declarator.span);
                    self.pat(&declarator.name);
                    if let Some(init) = &declarator.init {
                        self.expr(init);
                    }
                }
            }
            StmtKind::Expr(expr) | StmtKind::Throw(expr) | StmtKind::ExportAssign(expr) => {
                self.expr(expr)
            }
            StmtKind::Return(expr) => {
                if let Some(expr) = expr {
                    self.expr(expr);
                }
            }
            StmtKind::If(if_stmt) => {
                self.expr(&if_stmt.test);
                self.stmt(&if_stmt.consequent);
                if let Some(alternate) = &if_stmt.alternate {
                    self.stmt(alternate);
                }
            }
            StmtKind::While(while_stmt) => {
                self.expr(&while_stmt.test);
                self.stmt(&while_stmt.body);
            }
            StmtKind::DoWhile(do_while) => {
                self.stmt(&do_while.body);
                self.expr(&do_while.test);
            }
            StmtKind::For(for_stmt) => {
                match &for_stmt.init {
                    Some(ForInit::Var(var)) => {
                        for declarator in &var.declarations {
                            self.spans.push(declarator.span);
                            self.pat(&declarator.name);
                            if let Some(init) = &declarator.init {
                                self.expr(init);
                            }
                        }
                    }
                    Some(ForInit::Expr(expr)) => self.expr(expr),
                    None => {}
                }
                if let Some(test) = &for_stmt.test {
                    self.expr(test);
                }
                if let Some(update) = &for_stmt.update {
                    self.expr(update);
                }
                self.stmt(&for_stmt.body);
            }
            StmtKind::ForIn(for_in) => {
                self.for_left(&for_in.left);
                self.expr(&for_in.right);
                self.stmt(&for_in.body);
            }
            StmtKind::ForOf(for_of) => {
                self.for_left(&for_of.left);
                self.expr(&for_of.right);
                self.stmt(&for_of.body);
            }
            StmtKind::Switch(switch) => {
                self.expr(&switch.discriminant);
                for case in &switch.cases {
                    self.spans.push(case.span);
                    if let Some(test) = &case.test {
                        self.expr(test);
                    }
                    self.stmts(&case.consequent);
                }
            }
            StmtKind::Try(try_stmt) => {
                self.stmts(&try_stmt.block);
                if let Some(handler) = &try_stmt.handler {
                    self.spans.push(handler.span);
                    if let Some(param) = &handler.param {
                        self.pat(param);
                    }
                    self.stmts(&handler.body);
                }
                if let Some(finalizer) = &try_stmt.finalizer {
                    self.stmts(finalizer);
                }
            }
            StmtKind::Block(statements) => self.stmts(statements),
            StmtKind::FnDecl(function) => self.function(function),
            StmtKind::ClassDecl(class) => self.class(class),
            StmtKind::EnumDecl(enumeration) => {
                if let Some(span) = enumeration.name_span {
                    self.spans.push(span);
                }
                for member in &enumeration.members {
                    self.spans.push(member.span);
                    self.prop_name(&member.name);
                    if let Some(init) = &member.initializer {
                        self.expr(init);
                    }
                }
            }
            StmtKind::ModuleDecl(module) => {
                if let Some(span) = module.name_span {
                    self.spans.push(span);
                }
                match &module.body {
                    Some(ModuleBody::Block(statements)) => self.stmts(statements),
                    Some(ModuleBody::Module(inner)) => {
                        self.spans.push(inner.span);
                    }
                    None => {}
                }
            }
            StmtKind::Export(export) => match &export.kind {
                ExportDeclKind::Decl(inner) | ExportDeclKind::DefaultDecl(inner) => {
                    self.stmt(inner)
                }
                ExportDeclKind::Default(expr) => self.expr(expr),
                _ => {}
            },
            StmtKind::Labeled(labeled) => self.stmt(&labeled.body),
            StmtKind::With(with) => {
                self.expr(&with.object);
                self.stmt(&with.body);
            }
            StmtKind::Import(_)
            | StmtKind::ImportEquals(_)
            | StmtKind::InterfaceDecl(_)
            | StmtKind::TypeAlias(_)
            | StmtKind::Break(_)
            | StmtKind::Continue(_)
            | StmtKind::Empty
            | StmtKind::Debugger => {}
        }
    }

    fn for_left(&mut self, left: &ForInOfLeft) {
        match left {
            ForInOfLeft::Var(var) => {
                for declarator in &var.declarations {
                    self.spans.push(declarator.span);
                    self.pat(&declarator.name);
                }
            }
            ForInOfLeft::Pat(pat) => self.pat(pat),
            ForInOfLeft::Expr(expr) => self.expr(expr),
        }
    }

    fn function(&mut self, function: &FnDecl) {
        if let Some(span) = function.name_span {
            self.spans.push(span);
        }
        self.params(&function.params);
        if let Some(body) = &function.body {
            self.stmts(body);
            self.brace_tokens.push(function.span.end.saturating_sub(1));
        }
    }

    fn params(&mut self, params: &[Param]) {
        for param in params {
            self.spans.push(param.span);
            self.pat(&param.name);
            if let Some(init) = &param.initializer {
                self.expr(init);
            }
        }
    }

    fn class(&mut self, class: &ClassDecl) {
        if let Some(span) = class.name_span {
            self.spans.push(span);
        }
        if let Some(extends) = &class.extends {
            self.expr(extends);
        }
        for member in &class.members {
            self.spans.push(member.span);
            match &member.kind {
                ClassMemberKind::Property(prop) => {
                    self.prop_name(&prop.name);
                    if let Some(init) = &prop.initializer {
                        self.expr(init);
                    }
                }
                ClassMemberKind::Method(method) => {
                    self.prop_name(&method.name);
                    self.params(&method.params);
                    if let Some(body) = &method.body {
                        self.stmts(body);
                        self.brace_tokens.push(member.span.end.saturating_sub(1));
                    }
                }
                ClassMemberKind::Constructor(ctor) => {
                    self.params(&ctor.params);
                    if let Some(body) = &ctor.body {
                        self.stmts(body);
                        self.brace_tokens.push(member.span.end.saturating_sub(1));
                    }
                }
                ClassMemberKind::GetAccessor(accessor) | ClassMemberKind::SetAccessor(accessor) => {
                    self.prop_name(&accessor.name);
                    self.params(&accessor.params);
                    if let Some(body) = &accessor.body {
                        self.stmts(body);
                        self.brace_tokens.push(member.span.end.saturating_sub(1));
                    }
                }
                ClassMemberKind::StaticBlock(statements) => self.stmts(statements),
                ClassMemberKind::IndexSignature(_) | ClassMemberKind::SemicolonClassElement => {}
            }
        }
    }

    fn prop_name(&mut self, name: &PropName) {
        match name {
            PropName::Computed(expr, span) => {
                self.spans.push(*span);
                self.expr(expr);
            }
            _ => self.spans.push(name.span()),
        }
    }

    fn pat(&mut self, pat: &Pat) {
        self.spans.push(pat.span);
        match &pat.kind {
            PatKind::Ident(_) => {}
            PatKind::Array(elements) => {
                for element in elements.iter().flatten() {
                    match element {
                        ArrayPatElem::Pat(pat) | ArrayPatElem::Rest(pat) => self.pat(pat),
                    }
                }
            }
            PatKind::Object(props) => {
                for prop in props {
                    match prop {
                        ObjPatProp::KeyValue(name, pat) => {
                            self.prop_name(name);
                            self.pat(pat);
                        }
                        ObjPatProp::Shorthand(_, span) => self.spans.push(*span),
                        ObjPatProp::Rest(pat) => self.pat(pat),
                        ObjPatProp::ShorthandAssign(_, init, span) => {
                            self.spans.push(*span);
                            self.expr(init);
                        }
                    }
                }
            }
            PatKind::Assign(target, init) => {
                self.pat(target);
                self.expr(init);
            }
            PatKind::Rest(inner) => self.pat(inner),
        }
    }

    fn expr(&mut self, expr: &Expr) {
        self.spans.push(expr.span);
        match &expr.kind {
            ExprKind::Template(template) => {
                for expr in &template.exprs {
                    self.expr(expr);
                }
            }
            ExprKind::TaggedTemplate(tagged) => {
                self.expr(&tagged.tag);
                for expr in &tagged.quasi.exprs {
                    self.expr(expr);
                }
            }
            ExprKind::ArrayLit(elements) => {
                for element in elements.iter().flatten() {
                    self.expr(element);
                }
            }
            ExprKind::ObjectLit(props) => {
                for prop in props {
                    match prop {
                        ObjLitProp::Property(prop) => {
                            self.spans.push(prop.span);
                            self.prop_name(&prop.key);
                            self.expr(&prop.value);
                        }
                        ObjLitProp::Shorthand(_, span) => self.spans.push(*span),
                        ObjLitProp::ShorthandDefault(_, init, span) => {
                            self.spans.push(*span);
                            self.expr(init);
                        }
                        ObjLitProp::Spread(inner, span) => {
                            self.spans.push(*span);
                            self.expr(inner);
                        }
                        ObjLitProp::Method(method) => {
                            self.spans.push(method.span);
                            self.prop_name(&method.name);
                            self.params(&method.params);
                            self.stmts(&method.body);
                            self.brace_tokens.push(method.span.end.saturating_sub(1));
                        }
                        ObjLitProp::Get(accessor) | ObjLitProp::Set(accessor) => {
                            self.spans.push(accessor.span);
                            self.prop_name(&accessor.name);
                            self.params(&accessor.params);
                            self.stmts(&accessor.body);
                            self.brace_tokens.push(accessor.span.end.saturating_sub(1));
                        }
                    }
                }
            }
            ExprKind::FnExpr(function) => self.function(function),
            ExprKind::Arrow(arrow) => {
                self.params(&arrow.params);
                match &arrow.body {
                    ArrowBody::Expr(body) => self.expr(body),
                    ArrowBody::Block(body) => {
                        self.stmts(body);
                        self.brace_tokens.push(arrow.span.end.saturating_sub(1));
                    }
                }
            }
            ExprKind::ClassExpr(class) => self.class(class),
            ExprKind::Call(call) => {
                self.expr(&call.callee);
                for arg in &call.args {
                    self.expr(arg);
                }
            }
            ExprKind::New(new) => {
                self.expr(&new.callee);
                for arg in new.args.iter().flatten() {
                    self.expr(arg);
                }
            }
            ExprKind::Member(member) => self.expr(&member.object),
            ExprKind::ElemAccess(access) => {
                self.expr(&access.object);
                self.expr(&access.index);
            }
            ExprKind::Cond(cond) => {
                self.expr(&cond.test);
                self.expr(&cond.consequent);
                self.expr(&cond.alternate);
            }
            ExprKind::Binary(binary) => {
                self.expr(&binary.left);
                self.expr(&binary.right);
            }
            ExprKind::Assign(assign) => {
                self.expr(&assign.left);
                self.expr(&assign.right);
            }
            ExprKind::Unary(unary) => self.expr(&unary.argument),
            ExprKind::Update(update) => self.expr(&update.argument),
            ExprKind::Paren(inner)
            | ExprKind::NonNull(inner)
            | ExprKind::Spread(inner)
            | ExprKind::Await(inner)
            | ExprKind::Delete(inner)
            | ExprKind::Typeof(inner)
            | ExprKind::Void(inner) => self.expr(inner),
            ExprKind::TypeAssertion(assertion) => self.expr(&assertion.expr),
            ExprKind::As(as_expr) => self.expr(&as_expr.expr),
            ExprKind::Satisfies(satisfies) => self.expr(&satisfies.expr),
            ExprKind::Instantiation(instantiation) => self.expr(&instantiation.expr),
            ExprKind::Yield(_, inner) => {
                if let Some(inner) = inner {
                    self.expr(inner);
                }
            }
            ExprKind::Comma(exprs) => {
                for expr in exprs {
                    self.expr(expr);
                }
            }
            _ => {}
        }
    }
}

/// Byte ranges of output lines the module transform synthesizes: the
/// `exports.x = … = void 0;` hoist, the `__esModule` marker and AMD/System
/// wrapper headers.
fn synthetic_lines(js: &str) -> Vec<(usize, usize)> {
    let mut out = Vec::new();
    let mut start = 0;
    let system = js.contains("System.register(");
    // Inside a System.register wrapper, the wrapper's own scaffolding and
    // its hoisted `var` list (one level in) are synthesized too.
    let wrapper_line = |line: &str| {
        let indent = line.len() - line.trim_start().len();
        let text = line.trim();
        matches!(
            text,
            "return {"
                | "setters: [],"
                | "setters: ["
                | "execute: function () {"
                | "};"
                | "});"
                | "}"
                | "],"
        ) && indent <= 8
            || text.starts_with("var __moduleName = context_1")
            || (indent == 4
                && text.starts_with("var ")
                && text.ends_with(';')
                && text[4..text.len() - 1].split(", ").all(|name| {
                    name.chars()
                        .all(|c| c.is_alphanumeric() || c == '_' || c == '$')
                }))
    };
    for line in js.split_inclusive('\n') {
        let text = line.trim();
        if (text.starts_with("exports.") && text.ends_with("= void 0;"))
            || text.starts_with("Object.defineProperty(exports, \"__esModule\"")
            || text.starts_with("define(")
            || text.starts_with("System.register(")
            || (system && wrapper_line(line.trim_end_matches(['\n', '\r'])))
        {
            out.push((start, start + line.len()));
        }
        start += line.len();
    }
    out
}

/// Byte offsets of line starts, for (line, column) conversion; columns
/// count bytes on the line, and `\r\n` ends a line like `\n`.
struct LineStarts(Vec<usize>);

impl LineStarts {
    fn new(text: &str) -> Self {
        let mut starts = vec![0];
        for (index, byte) in text.bytes().enumerate() {
            if byte == b'\n' {
                starts.push(index + 1);
            }
        }
        Self(starts)
    }

    fn line_col(&self, offset: usize) -> (u32, u32) {
        let line = self.0.partition_point(|&start| start <= offset) - 1;
        (line as u32, (offset - self.0[line]) as u32)
    }
}

/// Comment ranges (`//…` and `/*…*/`), skipping string and template text.
fn comment_ranges(text: &str) -> Vec<Tok> {
    let mut out = Vec::new();
    scan(text, |tok, is_comment| {
        if is_comment {
            out.push(tok);
        }
    });
    out
}

/// Code tokens (no whitespace or comments).
fn tokenize(text: &str) -> Vec<Tok> {
    let mut out = Vec::new();
    scan(text, |tok, is_comment| {
        if !is_comment {
            out.push(tok);
        }
    });
    out
}

/// A lexical scan good enough for alignment: identifiers, numbers,
/// strings, templates (as one token), comments, and punctuation (common
/// multi-character operators as one token).
fn scan(text: &str, mut emit: impl FnMut(Tok, bool)) {
    const OPERATORS: [&str; 26] = [
        ">>>=", "...", "===", "!==", "**=", "<<=", ">>=", ">>>", "&&=", "||=", "??=", "=>", "==",
        "!=", "<=", ">=", "&&", "||", "??", "++", "--", "+=", "-=", "*=", "/=", "?.",
    ];
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        if b.is_ascii_whitespace() {
            i += 1;
            continue;
        }
        let start = i;
        if b == b'/' && bytes.get(i + 1) == Some(&b'/') {
            while i < bytes.len() && bytes[i] != b'\n' && bytes[i] != b'\r' {
                i += 1;
            }
            emit(Tok { start, end: i }, true);
            continue;
        }
        if b == b'/' && bytes.get(i + 1) == Some(&b'*') {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            i = (i + 2).min(bytes.len());
            emit(Tok { start, end: i }, true);
            continue;
        }
        if b == b'"' || b == b'\'' || b == b'`' {
            i += 1;
            while i < bytes.len() && bytes[i] != b {
                if bytes[i] == b'\\' {
                    i += 1;
                } else if b != b'`' && bytes[i] == b'\n' {
                    break;
                }
                i += 1;
            }
            i = (i + 1).min(bytes.len());
            emit(Tok { start, end: i }, false);
            continue;
        }
        if b.is_ascii_alphanumeric() || b == b'_' || b == b'$' || b >= 0x80 {
            while i < bytes.len()
                && (bytes[i].is_ascii_alphanumeric()
                    || bytes[i] == b'_'
                    || bytes[i] == b'$'
                    || bytes[i] >= 0x80
                    || (b.is_ascii_digit() && bytes[i] == b'.'))
            {
                i += 1;
            }
            emit(Tok { start, end: i }, false);
            continue;
        }
        let len = OPERATORS
            .iter()
            .find(|op| text[i..].starts_with(*op))
            .map_or(1, |op| op.len());
        i += len;
        emit(Tok { start, end: i }, false);
    }
}

/// For each source token, the output token it survives as: a patience
/// diff on token text (unique common tokens anchor the alignment; small
/// gaps between anchors are aligned exactly by LCS).
fn align_tokens(
    source: &str,
    src: &[Tok],
    js: &str,
    out: &[Tok],
    synthetic: &[(usize, usize)],
) -> Vec<Option<usize>> {
    let a: Vec<&str> = src.iter().map(|t| &source[t.start..t.end]).collect();
    // Tokens on lines only the module transform writes never align.
    let b: Vec<&str> = out
        .iter()
        .map(|t| {
            if synthetic
                .iter()
                .any(|(lo, hi)| *lo <= t.start && t.end <= *hi)
            {
                "\0"
            } else {
                &js[t.start..t.end]
            }
        })
        .collect();
    let mut result = vec![None; a.len()];
    patience(&a, &b, 0, a.len(), 0, b.len(), &mut result);
    result
}

fn patience(
    a: &[&str],
    b: &[&str],
    mut a_lo: usize,
    a_hi: usize,
    mut b_lo: usize,
    b_hi: usize,
    result: &mut [Option<usize>],
) {
    while a_lo < a_hi && b_lo < b_hi && a[a_lo] == b[b_lo] {
        result[a_lo] = Some(b_lo);
        a_lo += 1;
        b_lo += 1;
    }
    // No suffix trimming: synthesized trailers (an AMD wrapper's `});`)
    // would capture the last statement's tokens. Gaps prefer the earliest
    // output match instead.
    if a_lo == a_hi || b_lo == b_hi {
        return;
    }
    // Tokens occurring exactly once on each side.
    let mut counts: std::collections::HashMap<&str, (u32, u32, usize, usize)> =
        std::collections::HashMap::new();
    for (i, token) in a.iter().enumerate().take(a_hi).skip(a_lo) {
        let entry = counts.entry(token).or_insert((0, 0, 0, 0));
        entry.0 += 1;
        entry.2 = i;
    }
    for (j, token) in b.iter().enumerate().take(b_hi).skip(b_lo) {
        if let Some(entry) = counts.get_mut(token) {
            entry.1 += 1;
            entry.3 = j;
        }
    }
    let mut pairs: Vec<(usize, usize)> = counts
        .values()
        .filter(|(in_a, in_b, _, _)| *in_a == 1 && *in_b == 1)
        .map(|(_, _, i, j)| (*i, *j))
        .collect();
    pairs.sort_unstable();
    let anchors = longest_increasing(&pairs);
    if anchors.is_empty() {
        lcs(a, b, a_lo, a_hi, b_lo, b_hi, result);
        return;
    }
    let (mut prev_a, mut prev_b) = (a_lo, b_lo);
    for (i, j) in anchors {
        patience(a, b, prev_a, i, prev_b, j, result);
        result[i] = Some(j);
        prev_a = i + 1;
        prev_b = j + 1;
    }
    patience(a, b, prev_a, a_hi, prev_b, b_hi, result);
}

/// The longest chain of pairs increasing in both coordinates (pairs are
/// sorted by the first).
fn longest_increasing(pairs: &[(usize, usize)]) -> Vec<(usize, usize)> {
    let mut tails: Vec<usize> = Vec::new();
    let mut previous: Vec<Option<usize>> = vec![None; pairs.len()];
    for (index, &(_, j)) in pairs.iter().enumerate() {
        let position = tails.partition_point(|&tail| pairs[tail].1 < j);
        if position > 0 {
            previous[index] = Some(tails[position - 1]);
        }
        if position == tails.len() {
            tails.push(index);
        } else {
            tails[position] = index;
        }
    }
    let mut chain = Vec::new();
    let mut cursor = tails.last().copied();
    while let Some(index) = cursor {
        chain.push(pairs[index]);
        cursor = previous[index];
    }
    chain.reverse();
    chain
}

/// Exact LCS alignment for a gap; very large gaps are left unaligned.
fn lcs(
    a: &[&str],
    b: &[&str],
    a_lo: usize,
    a_hi: usize,
    b_lo: usize,
    b_hi: usize,
    result: &mut [Option<usize>],
) {
    let (n, m) = (a_hi - a_lo, b_hi - b_lo);
    if n.saturating_mul(m) > 4_000_000 {
        return;
    }
    let mut table = vec![0u32; (n + 1) * (m + 1)];
    let at = |i: usize, j: usize| i * (m + 1) + j;
    for i in (0..n).rev() {
        for j in (0..m).rev() {
            table[at(i, j)] = if a[a_lo + i] == b[b_lo + j] {
                table[at(i + 1, j + 1)] + 1
            } else {
                table[at(i + 1, j)].max(table[at(i, j + 1)])
            };
        }
    }
    let (mut i, mut j) = (0, 0);
    while i < n && j < m {
        if a[a_lo + i] == b[b_lo + j] {
            result[a_lo + i] = Some(b_lo + j);
            i += 1;
            j += 1;
        } else if table[at(i + 1, j)] >= table[at(i, j + 1)] {
            i += 1;
        } else {
            j += 1;
        }
    }
}
